[context.production.environment]
  HUGO_VERSION = "0.65.3"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.65.3"

[build]
  command = "hugo  --destination public --i18n-warnings --verbose"
  publish = "public/"
